### ISSUE TITLE
JBake 2.3.0/2.3.1 fail with AsciidoctorJ 1.5.0

### ISSUE THREAD

**Issue by aalmiray** [jbake-org/jbake#130]
The following exception is thrown if asciidoctorj-1.5.0 is in the classpath

```
Caused by: java.lang.NoSuchMethodError: org.asciidoctor.Asciidoctor.readDocumentHeader(Ljava/io/File;)Lorg/asciidoctor/DocumentHeader;
    at org.jbake.parser.AsciidoctorEngine.processHeader(AsciidoctorEngine.java:73)
    at org.jbake.app.Parser.processFile(Parser.java:86)
    at org.jbake.app.Crawler.crawlSourceFile(Crawler.java:116)
    at org.jbake.app.Crawler.crawl(Crawler.java:82)
    at org.jbake.app.Oven.bake(Oven.java:130)
    at me.champeau.gradle.JBakeTask$_bake_closure1.doCall(JBakeTask.groovy:38)
    at me.champeau.gradle.JBakeTask.bake(JBakeTask.groovy:35)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 44 more
```

**Comment by RobWin** [comment]
Hi,

i'm using thee following Gradle plugins and I have the same issue like @aalmiray

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'me.champeau.gradle:jbake-gradle-plugin:0.2'
        classpath 'org.asciidoctor:asciidoctorj:1.5.2'
        classpath 'org.freemarker:freemarker:2.3.19'
    }
}
