### ISSUE TITLE
JBake Gradle Plugin fails in AsciidoctorEngine.processHeader

### ISSUE THREAD

**Issue by RobWin** [jbake-org/jbake#176]
Hi,

i'm using the following Gradle plugins and I have the same issue like @aalmiray

```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'me.champeau.gradle:jbake-gradle-plugin:0.2'
        classpath 'org.asciidoctor:asciidoctorj:1.5.2'
        classpath 'org.freemarker:freemarker:2.3.19'
    }
}
```
```
Caused by: java.lang.NoSuchMethodError: org.asciidoctor.Asciidoctor.readDocumentHeader(Ljava/io/File;)Lorg/asciidoctor/DocumentHeader;
        at org.jbake.parser.AsciidoctorEngine.processHeader(AsciidoctorEngine.java:73)
        at org.jbake.app.Parser.processFile(Parser.java:86)
        at org.jbake.app.Crawler.crawlSourceFile(Crawler.java:116)
        at org.jbake.app.Crawler.crawl(Crawler.java:82)
        at org.jbake.app.Crawler.crawl(Crawler.java:87)
        at org.jbake.app.Crawler.crawl(Crawler.java:87)
        at org.jbake.app.Oven.bake(Oven.java:130)
        at me.champeau.gradle.JBakeTask$_bake_closure1.doCall(JBakeTask.groovy:38)
        at me.champeau.gradle.JBakeTask.bake(JBakeTask.groovy:35)
```
Kind regards,
Robert Winkler

**Comment by RobWin** [comment]
ok. I found this Gist
https://gist.github.com/aalmiray/1e38835b75d646d00e51

classpath 'org.jbake:jbake-core:2.3.2' was missing in dependencies.
But why is this not automatically included?

**Comment by jonbullock** [comment]
With the added line in the dependencies does this resolve the stacktrace?

I've not tested JBake against Asciidoctor v1.5.2 yet, I was planning on adding support for it in the next release though.

**Comment by RobWin** [comment]
Yes it solved the issue.
