### ISSUE TITLE
Tagcloud: Number of posts per tag

### ISSUE THREAD

**Issue by uli-heller** [jbake-org/jbake#216]
I'm doing a tagcloud on my blog. For this, I need the number of posts per tag.
I didn't find a documented way to get this number, so I'm using

```
db.getPublishedPostsByTag(tag).size()
```

within one of my gsp templates for now.

Does it make sense to create a public object and method for this? Similar to "alltags"? Or an extension to it?

**Comment by jonbullock** [comment]
Yeah that sounds like a great idea.

**Comment by manikmagar** [comment]
@jonbullock  Accessing `${db.getPublishedPostsByTag(tagname)}` throws below exception in Freemarker template. Is there a different way of accessing db for freemarker? 


JBake failed with 1 errors:
1. java.lang.Exception: Failed to render index. Cause: Failed to render index.html

org.jbake.app.JBakeException: JBake failed with 1 errors:
1. java.lang.Exception: Failed to render index. Cause: Failed to render index.html

	at org.jbake.launcher.Baker.bake(Baker.java:32)
	at org.jbake.launcher.Main.run(Main.java:95)
	at org.jbake.launcher.Main.run(Main.java:81)
	at org.jbake.launcher.Main.main(Main.java:34)
Caused by: org.jbake.template.RenderingException: java.lang.Exception: Failed to render index. Cause: Failed to render index.html
	at org.jbake.render.IndexRenderer.render(IndexRenderer.java:25)
	at org.jbake.app.Oven.bake(Oven.java:151)
	at org.jbake.launcher.Baker.bake(Baker.java:20)
	... 3 more
Caused by: java.lang.Exception: Failed to render index. Cause: Failed to render index.html
	at org.jbake.app.Renderer.renderIndexPaging(Renderer.java:295)
	at org.jbake.render.IndexRenderer.render(IndexRenderer.java:19)
	... 5 more
Caused by: java.lang.Exception: Failed to render index.html
	at org.jbake.app.Renderer.render(Renderer.java:243)
	at org.jbake.app.Renderer.renderIndexPaging(Renderer.java:291)
	... 6 more
Caused by: java.lang.ClassCastException: org.jbake.app.ContentStore cannot be cast to java.util.Collection
	at org.jbake.template.FreemarkerTemplateEngine$LazyLoadingModel$1.adapt(FreemarkerTemplateEngine.java:92)
	at org.jbake.template.FreemarkerTemplateEngine$LazyLoadingModel$1.adapt(FreemarkerTemplateEngine.java:1)
	at org.jbake.template.ModelExtractors.extractAndTransform(ModelExtractors.java:120)
	at org.jbake.template.FreemarkerTemplateEngine$LazyLoadingModel.get(FreemarkerTemplateEngine.java:82)
	at freemarker.core.Environment.getGlobalVariable(Environment.java:1912)
	at freemarker.core.Environment.getVariable(Environment.java:1899)
	at freemarker.core.Identifier._eval(Identifier.java:39)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:81)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:59)
	at freemarker.core.Environment.visit(Environment.java:363)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:292)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:272)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:243)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:596)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:327)
	at freemarker.core.Environment.visit(Environment.java:333)
	at freemarker.core.Environment.visit(Environment.java:333)
	at freemarker.core.Environment.include(Environment.java:2509)
	at freemarker.core.Include.accept(Include.java:171)
	at freemarker.core.Environment.visit(Environment.java:327)
	at freemarker.core.Environment.visit(Environment.java:333)
	at freemarker.core.Environment.process(Environment.java:306)
	at freemarker.template.Template.process(Template.java:386)
	at org.jbake.template.FreemarkerTemplateEngine.renderDocument(FreemarkerTemplateEngine.java:59)
	at org.jbake.template.DelegatingTemplateEngine.renderDocument(DelegatingTemplateEngine.java:65)
	at org.jbake.app.Renderer.render(Renderer.java:236)
	... 7 more
