### ISSUE TITLE
File watch mode is broken

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#253]
File watch mode is broken in master branch.

The following is shown when used:

```
JBake v2.5.0-SNAPSHOT (2015-12-29 21:14:25PM) [http://jbake.org]

Dec 29, 2015 9:23:33 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "/var/folders/v0/182c_jnx7995z6z86c648n640000gn/T/vfs_cache" as temporary files store.
org.apache.commons.vfs2.FileSystemException: Could not find file with URI "./content" because it is a relative path, and no base URI was provided.
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:719)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:649)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:605)
	at org.jbake.launcher.Main.startWatch(Main.java:160)
	at org.jbake.launcher.Main.run(Main.java:99)
	at org.jbake.launcher.Main.main(Main.java:41)
21:23:34.057 INFO  org.jbake.launcher.JettyServer - Serving out contents of: [output] on http://localhost:8820/
21:23:34.060 INFO  org.jbake.launcher.JettyServer - (To stop server hit CTRL-C)
```

Raised by @bodiam via Twitter.

**Comment by bodiam** [comment]
In the Main.java, change the listenPath line (line 160) to the following:

````
FileObject listenPath = fsMan.resolveFile(res.getSource(), config.getString(Keys.CONTENT_FOLDER));
````

This seems to fix the issue.

**Comment by jonbullock** [comment]
Excellent thanks @bodiam
