### ISSUE TITLE
jbake-master: "jbake -b" shows java.util.NoSuchElementException: 'index.paginate'...

### ISSUE THREAD

**Issue by uli-heller** [jbake-org/jbake#332]
* jbake-2.5.0: No error/warning
* jbake-master: Displays an error/warning

```
$ jbake -b
...
07:22:19.167 INFO  org.jbake.app.Asset - Copying [./assets/js/i2ui-1.0.0.js]...done!
07:22:19.168 INFO  org.jbake.app.Asset - Copying [./assets/js/jquery-1.11.1.min.js]...done!
07:22:19.170 INFO  org.jbake.app.Asset - Copying [./assets/js/prettify.js]...done!
07:22:19.171 INFO  org.jbake.app.Oven - Baking finished!
07:22:19.173 INFO  org.jbake.app.Oven - Baked 188 items in 56361ms
07:22:19.173 ERROR org.jbake.app.Oven - Failed to bake 1 item(s)!
07:22:19.215 INFO  c.o.orient.core.Orient - - storage: cache...
07:22:19.247 INFO  c.o.orient.core.Orient - OrientDB Engine shutdown complete
JBake failed with 1 errors:
1. java.util.NoSuchElementException: 'index.paginate' doesn't map to an existing object

org.jbake.app.JBakeException: JBake failed with 1 errors:
1. java.util.NoSuchElementException: 'index.paginate' doesn't map to an existing object

	at org.jbake.launcher.Baker.bake(Baker.java:32)
	at org.jbake.launcher.Main.run(Main.java:95)
	at org.jbake.launcher.Main.run(Main.java:81)
	at org.jbake.launcher.Main.main(Main.java:34)
Caused by: org.jbake.template.RenderingException: java.util.NoSuchElementException: 'index.paginate' doesn't map to an existing object
	at org.jbake.render.IndexRenderer.render(IndexRenderer.java:24)
	at org.jbake.app.Oven.bake(Oven.java:151)
	at org.jbake.launcher.Baker.bake(Baker.java:20)
	... 3 more
Caused by: java.util.NoSuchElementException: 'index.paginate' doesn't map to an existing object
	at org.apache.commons.configuration.AbstractConfiguration.getBoolean(AbstractConfiguration.java:644)
	at org.jbake.render.IndexRenderer.render(IndexRenderer.java:17)
	... 5 more
```

**Comment by jonbullock** [comment]
Thanks for reporting this... I'll have to investigate this further to see what is going on.

**Comment by ancho** [comment]
I Can confirm the same behavior. IndexRenderer tries to access a configuration property which is not present in that case.

We should fallback to normal index rendering if the property is not set. I will fix that.

**Comment by jonbullock** [comment]
Thanks @ancho 👍
