### ISSUE TITLE
Baking process is not possible with Java 9

### ISSUE THREAD

**Issue by tuxtor** [jbake-org/jbake#408]
I'm using a fresh JBake (2.5.1 SDKMan) installation over Fedora 26 and the newly released Oracle JDK 9.

So far when I use JDK 9 to trigger baking process I'm receiving this as output:

> $ jbake -b 
> JBake v2.5.1 (2017-01-31 23:24:52PM) [http://jbake.org]
> 
> 19:37:56.676 WARN  c.o.o.c.d.r.ODatabaseRecordAbstract$2 - Current implementation of storage does not support sbtree collections
> An unexpected error occurred: Cannot create database

However If i switch to JDK 8 (Oracle and OpenJDK) all works properly.

**Comment by ancho** [comment]
Hello @tuxtor. We are switching to a newer version of orient db. See #337. The pull request is quite old. The newest version in 2.x is 2.2.28.
There is an open issue at orientdb https://github.com/orientechnologies/orientdb/issues/7780 addressing problems with jdk 9.

I made a quick test with 2.2.28. There are several warnings from orientdb but baking a site was successful. So we need to be patient and wait for orientdb to fix the jdk9 issues.

```
JBake v2.6.0-SNAPSHOT (2017-10-01 10:29:28vorm.) [http://jbake.org]

10:45:31.581 WARN  c.o.common.util.OMemory - Unable to determine the amount of installed RAM.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @70f02c32
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.orientechnologies.common.util.OMemory.getPhysicalMemorySize(OMemory.java:65)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEnginesInitializer.java:79)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitializer.java:62)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:51)
	at com.orientechnologies.orient.core.engine.memory.OEngineMemory.startup(OEngineMemory.java:62)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:882)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:475)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at org.jbake.app.ContentStore.<init>(ContentStore.java:61)
	at org.jbake.app.DBUtil.createDataStore(DBUtil.java:15)
	at org.jbake.app.Oven.bake(Oven.java:132)
	at org.jbake.launcher.Baker.bake(Baker.java:20)
	at org.jbake.launcher.Main.run(Main.java:97)
	at org.jbake.launcher.Main.run(Main.java:82)
	at org.jbake.launcher.Main.main(Main.java:36)
10:45:31.585 WARN  c.o.o.c.e.OMemoryAndLocalPaginatedEnginesInitializer - Not enough physical memory available for DISKCACHE: 0MB (heap=4.946MB direct=512MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB
10:45:31.586 INFO  c.o.o.c.e.OMemoryAndLocalPaginatedEnginesInitializer - OrientDB config DISKCACHE=256MB (heap=4.946MB direct=512MB os=0MB)
10:45:31.587 WARN  c.o.common.util.OMemory - Unable to determine the amount of installed RAM.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @70f02c32
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.orientechnologies.common.util.OMemory.getPhysicalMemorySize(OMemory.java:65)
	at com.orientechnologies.common.util.OMemory.checkDirectMemoryConfiguration(OMemory.java:140)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:53)
	at com.orientechnologies.orient.core.engine.memory.OEngineMemory.startup(OEngineMemory.java:62)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:882)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:475)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at org.jbake.app.ContentStore.<init>(ContentStore.java:61)
	at org.jbake.app.DBUtil.createDataStore(DBUtil.java:15)
	at org.jbake.app.Oven.bake(Oven.java:132)
	at org.jbake.launcher.Baker.bake(Baker.java:20)
	at org.jbake.launcher.Main.run(Main.java:97)
	at org.jbake.launcher.Main.run(Main.java:82)
	at org.jbake.launcher.Main.main(Main.java:36)
10:45:31.588 WARN  c.o.common.util.OMemory - Unable to determine the amount of installed RAM.
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @70f02c32
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.orientechnologies.common.util.OMemory.getPhysicalMemorySize(OMemory.java:65)
	at com.orientechnologies.common.util.OMemory.checkCacheMemoryConfiguration(OMemory.java:164)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:55)
	at com.orientechnologies.orient.core.engine.memory.OEngineMemory.startup(OEngineMemory.java:62)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:882)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:475)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at org.jbake.app.ContentStore.<init>(ContentStore.java:61)
	at org.jbake.app.DBUtil.createDataStore(DBUtil.java:15)
	at org.jbake.app.Oven.bake(Oven.java:132)
	at org.jbake.launcher.Baker.bake(Baker.java:20)
	at org.jbake.launcher.Main.run(Main.java:97)
	at org.jbake.launcher.Main.run(Main.java:82)
	at org.jbake.launcher.Main.main(Main.java:36)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/tmp/jbake-2.6.0-SNAPSHOT-bin/lib/orientdb-core-2.2.28.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:45:33.010 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: masterindex
10:45:33.010 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: tag
10:45:33.010 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: sitemap
10:45:33.133 INFO  org.jbake.app.Oven - Baking has started...
10:45:33.235 INFO  org.jbake.app.Crawler - Processing [/tmp/test/content/about.html]...  : new 
10:45:33.248 INFO  org.jbake.app.Crawler - Processing [/tmp/test/content/blog/2013/first-post.html]...  : new 
10:45:33.267 INFO  org.jbake.parser.AsciidoctorEngine - Initializing Asciidoctor engine...
10:45:35.433 INFO  org.jbake.parser.AsciidoctorEngine - Asciidoctor engine initialized.
10:45:35.871 INFO  org.jbake.app.Crawler - Processing [/tmp/test/content/blog/2013/fourth-post.adoc]...  : new 
10:45:36.189 INFO  org.jbake.app.Crawler - Processing [/tmp/test/content/blog/2013/second-post.md]...  : new 
10:45:36.233 INFO  org.jbake.app.Crawler - Processing [/tmp/test/content/blog/2013/third-post.adoc]...  : new 
10:45:36.234 INFO  org.jbake.app.Oven - Content detected:
10:45:36.234 INFO  org.jbake.app.Oven - Parsed 1 files of type: page
10:45:36.238 INFO  org.jbake.app.Oven - Parsed 4 files of type: post
10:45:37.024 INFO  org.jbake.app.Renderer - Rendering archive [./output/archive.html]...done!
10:45:37.037 INFO  org.jbake.app.Renderer - Rendering [./output/about.html]... done!
10:45:37.047 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/fourth-post.html]... done!
10:45:37.058 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/third-post.html]... done!
10:45:37.063 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/second-post.html]... done!
10:45:37.069 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/first-post.html]... done!
10:45:37.085 INFO  org.jbake.app.Renderer - Rendering feed [./output/feed.xml]...done!
10:45:37.097 INFO  org.jbake.app.Renderer - Rendering masterindex [./output/index.html]...done!
10:45:37.112 INFO  org.jbake.app.Renderer - Rendering sitemap [./output/sitemap.xml]...done!
10:45:37.147 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/css/asciidoctor.css]... done!
10:45:37.147 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/css/base.css]... done!
10:45:37.148 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/css/bootstrap.min.css]... done!
10:45:37.148 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/css/prettify.css]... done!
10:45:37.149 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/favicon.ico]... done!
10:45:37.149 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/fonts/glyphicons-halflings-regular.eot]... done!
10:45:37.149 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/fonts/glyphicons-halflings-regular.svg]... done!
10:45:37.150 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/fonts/glyphicons-halflings-regular.ttf]... done!
10:45:37.150 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/fonts/glyphicons-halflings-regular.woff]... done!
10:45:37.150 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/js/bootstrap.min.js]... done!
10:45:37.151 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/js/html5shiv.min.js]... done!
10:45:37.151 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/js/jquery-1.11.1.min.js]... done!
10:45:37.151 INFO  org.jbake.app.Asset - Copying [/tmp/test/assets/js/prettify.js]... done!
10:45:37.152 INFO  org.jbake.app.Oven - Baking finished!
10:45:37.152 INFO  org.jbake.app.Oven - Baked 9 items in 4019ms
10:45:37.153 INFO  c.o.orient.core.Orient - Orient Engine is shutting down...
10:45:37.153 INFO  c.o.orient.core.Orient - - shutdown storage: cache...
10:45:37.320 INFO  c.o.orient.core.Orient - OrientDB Engine shutdown complete
```

**Comment by AlanBateman** [comment]
From the exception, I assume com.orientechnologies.common.util.OMemory.getPhysicalMemorySize is trying to invoke getTotalPhysicalMemorySize on the internal  implementation class, it should invoke it on the OperatingSystemMXBean interface.

**Comment by ancho** [comment]
Thanks Alan, see https://github.com/orientechnologies/orientdb/issues/7780#issuecomment-333587905.
They will fix it.

**Comment by ancho** [comment]
I checked with openjdk Zulu build 9.0.1.3+11 and orientdb 2.2.30.
It's getting better. Still a warning left, though.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/tmp/jbake-2.6.0-SNAPSHOT-bin/lib/orientdb-core-2.2.30.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

```
frank@slappy /tmp/jbake-java9                                                                              [19:37:43] 
> $ java -version                                                                                                    
openjdk version "9.0.1.3"
OpenJDK Runtime Environment (Zulu build 9.0.1.3+11)
OpenJDK 64-Bit Server VM (Zulu build 9.0.1.3+11, mixed mode)
                                                                                                                      
frank@slappy /tmp/jbake-java9                                                                              [19:37:49] 
> $ ../jbake-2.6.0-SNAPSHOT-bin/bin/jbake -b                                                                         
JBake v2.6.0-SNAPSHOT (2018-01-16 19:28:29PM) [http://jbake.org]

19:38:12.870 INFO  c.o.o.c.e.OMemoryAndLocalPaginatedEnginesInitializer - Auto configuration of disk cache size.
19:38:13.028 INFO  c.o.common.jna.ONative - 20743299072 B/19782 MB/19 GB of physical memory were detected on machine
19:38:13.036 INFO  c.o.common.jna.ONative - Soft memory limit for this process is set to -1 B/-1 MB/-1 GB
19:38:13.037 INFO  c.o.common.jna.ONative - Hard memory limit for this process is set to -1 B/-1 MB/-1 GB
19:38:13.038 INFO  c.o.common.jna.ONative - Path to 'memory' cgroup is '/user.slice'
19:38:13.041 INFO  c.o.common.jna.ONative - Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory'
19:38:13.041 INFO  c.o.common.jna.ONative - cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB
19:38:13.042 INFO  c.o.common.jna.ONative - cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB
19:38:13.042 INFO  c.o.common.jna.ONative - Detected memory limit for current process is 20743299072 B/19782 MB/19 GB
19:38:13.047 INFO  c.o.o.c.e.OMemoryAndLocalPaginatedEnginesInitializer - OrientDB auto-config DISKCACHE=512MB (heap=4.946MB direct=512MB os=19.782MB)
19:38:13.058 INFO  c.o.o.c.config.OGlobalConfiguration - Lowering disk cache size from 512MB to 510MB.
19:38:13.059 INFO  c.o.o.c.config.OGlobalConfiguration - Lowering memory chunk size from 536.870.912B to 534.773.760B.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/tmp/jbake-2.6.0-SNAPSHOT-bin/lib/orientdb-core-2.2.30.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
19:38:13.238 INFO  c.o.o.c.s.i.m.ODirectMemoryStorage - $ANSI{green {db=cache}} Storage 'memory:cache' is created under OrientDB distribution : 2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x)
19:38:14.517 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: masterindex
19:38:14.517 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: tagsindex
19:38:14.518 INFO  org.jbake.template.ModelExtractors - register new extractors for document type: sitemap
19:38:14.717 INFO  org.jbake.app.Oven - Baking has started...
19:38:14.868 INFO  org.jbake.app.Crawler - Processing [/tmp/jbake-java9/content/about.html]...  : new 
19:38:14.882 INFO  org.jbake.app.Crawler - Processing [/tmp/jbake-java9/content/blog/2013/first-post.html]...  : new 
19:38:14.900 INFO  org.jbake.parser.AsciidoctorEngine - Initializing Asciidoctor engine...
19:38:17.270 INFO  org.jbake.parser.AsciidoctorEngine - Asciidoctor engine initialized.
19:38:17.700 INFO  org.jbake.app.Crawler - Processing [/tmp/jbake-java9/content/blog/2013/fourth-post.adoc]...  : new 
19:38:17.849 INFO  org.jbake.app.Crawler - Processing [/tmp/jbake-java9/content/blog/2013/second-post.md]...  : new 
19:38:17.891 INFO  org.jbake.app.Crawler - Processing [/tmp/jbake-java9/content/blog/2013/third-post.adoc]...  : new 
19:38:17.891 INFO  org.jbake.app.Oven - Content detected:
19:38:17.891 INFO  org.jbake.app.Oven - Parsed 1 files of type: page
19:38:17.893 INFO  org.jbake.app.Oven - Parsed 4 files of type: post
19:38:18.628 INFO  org.jbake.app.Renderer - Rendering archive [./output/archive.html]...done!
19:38:18.642 INFO  org.jbake.app.Renderer - Rendering [./output/about.html]... done!
19:38:18.654 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/fourth-post.html]... done!
19:38:18.661 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/third-post.html]... done!
19:38:18.668 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/second-post.html]... done!
19:38:18.672 INFO  org.jbake.app.Renderer - Rendering [./output/blog/2013/first-post.html]... done!
19:38:18.690 INFO  org.jbake.app.Renderer - Rendering feed [./output/feed.xml]...done!
19:38:18.704 INFO  org.jbake.app.Renderer - Rendering masterindex [./output/index.html]...done!
19:38:18.721 INFO  org.jbake.app.Renderer - Rendering sitemap [./output/sitemap.xml]...done!
19:38:18.763 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/css/asciidoctor.css]... done!
19:38:18.764 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/css/base.css]... done!
19:38:18.764 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/css/bootstrap.min.css]... done!
19:38:18.765 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/css/prettify.css]... done!
19:38:18.765 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/favicon.ico]... done!
19:38:18.767 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/fonts/glyphicons-halflings-regular.eot]... done!
19:38:18.768 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/fonts/glyphicons-halflings-regular.svg]... done!
19:38:18.768 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/fonts/glyphicons-halflings-regular.ttf]... done!
19:38:18.768 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/fonts/glyphicons-halflings-regular.woff]... done!
19:38:18.769 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/js/bootstrap.min.js]... done!
19:38:18.770 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/js/html5shiv.min.js]... done!
19:38:18.770 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/js/jquery-1.11.1.min.js]... done!
19:38:18.770 INFO  org.jbake.app.Asset - Copying [/tmp/jbake-java9/assets/js/prettify.js]... done!
19:38:18.771 INFO  org.jbake.app.Oven - Baking finished!
19:38:18.771 INFO  org.jbake.app.Oven - Baked 9 items in 4054ms
19:38:18.772 INFO  c.o.orient.core.Orient - Orient Engine is shutting down...
19:38:18.773 INFO  c.o.orient.core.Orient - - shutdown storage: cache...
19:38:18.933 INFO  c.o.orient.core.Orient - OrientDB Engine shutdown complete
```

**Comment by jonbullock** [comment]
Done as part of #424
