### ISSUE TITLE
Calling #vars.getVariable() in thymeleaf-template fails with stacktrace (regression)

### ISSUE THREAD

**Issue by McNetic** [jbake-org/jbake#434]
With 2.5.1, I can do (for a simple example) something like this:
```
<table>
<tr th:each="var : ${#vars.getVariableNames()}">
            <td th:text="${var}"></td>
            <td th:text="${#vars.getVariable(var)}"></td>
        </tr>
</table>
```
With 2.6.0, this does no longer work; calling #vars.getVariable() fails with the following stacktrace:
```
08:47:49.255 ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][main] Exception processing template "team.html": Exception evaluating OGNL expression: "#vars.getVariable(var)" (template: "team.html" - line 80, col 17)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "#vars.getVariable(var)" (template: "team.html" - line 80, col 17)
        at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191)
        at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95)
        at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:165)
        at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
        at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
        at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
        at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:126)
        at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
        at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
        at org.thymeleaf.engine.Model.process(Model.java:282)
        at org.thymeleaf.engine.Model.process(Model.java:290)
        at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:367)
        at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:293)
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640)
        at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
        at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1067)
        at org.jbake.template.ThymeleafTemplateEngine.renderDocument(ThymeleafTemplateEngine.java:80)
        at org.jbake.template.DelegatingTemplateEngine.renderDocument(DelegatingTemplateEngine.java:61)
        at org.jbake.app.Renderer.render(Renderer.java:207)
        at org.jbake.render.DocumentsRenderer.render(DocumentsRenderer.java:50)
        at org.jbake.app.Oven.bake(Oven.java:155)
        at org.jbake.launcher.Baker.bake(Baker.java:20)
        at org.jbake.launcher.Main.run(Main.java:97)
        at org.jbake.launcher.Main.run(Main.java:82)
        at org.jbake.launcher.Main.main(Main.java:36)
Caused by: ognl.MethodFailedException: Method "getVariable" failed for object 
{all_content=...}[StandardHTMLInliner](team.html)
        at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1551)
        at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
        at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1615)
        at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTChain.getValueBody(ASTChain.java:141)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.Ognl.getValue(Ognl.java:467)
        at ognl.Ognl.getValue(Ognl.java:431)
        at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:316)
        at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170)
        ... 30 common frames omitted
Caused by: java.lang.ClassCastException: org.jbake.app.ContentStore cannot be cast to org.jbake.app.DocumentList
        at org.jbake.template.ThymeleafTemplateEngine$JBakeMap$1$3.loadValue(ThymeleafTemplateEngine.java:117)
        at org.jbake.template.ThymeleafTemplateEngine$JBakeMap$1$3.loadValue(ThymeleafTemplateEngine.java:114)
        at org.thymeleaf.context.LazyContextVariable.getValue(LazyContextVariable.java:84)
        at org.thymeleaf.context.EngineContext.resolveLazy(EngineContext.java:602)
        at org.thymeleaf.context.EngineContext.getVariable(EngineContext.java:194)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:894)
        at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1539)
        ... 42 common frames omitted
```

**Comment by ancho** [comment]
Thanks for raising this issue.

**Comment by McNetic** [comment]
It works again with the snapshot build, thank you very much.
