### ISSUE TITLE
OrientDB threw IllegalArgumentException: Cluster name is empty

### ISSUE THREAD

**Issue by OndraZizka** [jbake-org/jbake#488]
I ran JBake 2.6.1 on a directory with previously saved cache.
And got the following exception.

I'm capturing it in case someone knows what that could be.
And I suggest (and offer) to handle the exception gracefully (i.e. catch at some point in JBake).

```
00:24:49.693 INFO  org.jbake.app.Crawler - Processing [/home/ondra/uw/oz.cz/jbake-based/content/blog/2018/test.texy]...  : same 
00:24:49.837 ERROR unknown.jul.logger - Exception `09BD0FA6` in storage `plocal:cache`: 2.2.33 (build 77584cd6827f647cf4aa231cf27bd6f10bc04e2c, branch 2.2.x)
java.lang.IllegalArgumentException: Cluster name is empty
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:1696)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getClusterIdByName(ODatabaseDocumentTx.java:1340)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1228)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:992)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.getOrCreateClass(OSchemaShared.java:299)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.getOrCreateClass(OSchemaShared.java:269)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.getOrCreateClass(OSchemaProxy.java:82)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.getOrCreateClass(OSchemaProxy.java:71)
        at com.orientechnologies.orient.core.record.impl.ODocument.setClassName(ODocument.java:2009)
        at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:161)
        at org.jbake.app.Crawler.crawlSourceFile(Crawler.java:209)
        at org.jbake.app.Crawler.crawl(Crawler.java:113)
        at org.jbake.app.Crawler.crawl(Crawler.java:118)
        at org.jbake.app.Oven.bake(Oven.java:142)
        at org.jbake.launcher.Baker.bake(Baker.java:20)
        at org.jbake.launcher.Main.run(Main.java:97)
        at org.jbake.launcher.Main.run(Main.java:82)
        at org.jbake.launcher.Main.main(Main.java:36)
```

**Comment by OndraZizka** [comment]
PS: I hope I don't spam you too much with issues :)
But when filing them, I am also willing to fix them. I only need some approval that it's not something that will be overhauled for 3.0 anyway, so fixing it now wouldn't be worth it.

**Comment by jonbullock** [comment]
I'm guessing the OrientDB stacktrace is related to the lack of value for `default.type` but we definitely need to resolve the fact you could get that far without a value set.

Always good to see somebody new joining the community... it's just taking me a while to get through the backlog ;-)

**Comment by jonbullock** [comment]
Related issue: #481
