### ISSUE TITLE
Switch some tests db storage to plocal - Travis tests sometimes run out of memory.

### ISSUE THREAD

**Issue by OndraZizka** [jbake-org/jbake#527]
The Travis jobs sometimes run out of memory, see below.
For instance here: https://travis-ci.org/jbake-org/jbake/jobs/411522338

Switching to `plocal`, however, makes the tests run around 4 times longer.

```
org.jbake.app.template.GroovyMarkupTemplateEngineRenderingTest STANDARD_OUT
    00:05:07.184 ERROR unknown.jul.logger - Exception `71D06574` in storage `memory:documents1533254706562`: 2.2.33 (build 77584cd6827f647cf4aa231cf27bd6f10bc04e2c, branch 2.2.x)
    java.lang.OutOfMemoryError: Direct buffer memory
    	at java.base/java.nio.Bits.reserveMemory(Bits.java:187)
    	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
    	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:310)
    	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:410)
    	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:361)
    	at com.orientechnologies.orient.core.storage.impl.memory.ODirectMemoryOnlyDiskCache$MemoryFile.addNewPage(ODirectMemoryOnlyDiskCache.java:495)
    	at com.orientechnologies.orient.core.storage.impl.memory.ODirectMemoryOnlyDiskCache$MemoryFile.access$200(ODirectMemoryOnlyDiskCache.java:458)
    	at com.orientechnologies.orient.core.storage.impl.memory.ODirectMemoryOnlyDiskCache.allocateNewPage(ODirectMemoryOnlyDiskCache.java:247)
    	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:434)
    	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:468)
    	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:412)
    	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116)
    	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:193)
    	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:4349)
    	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:4330)
    	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:486)
    	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:439)
    	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:399)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:305)
    	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
    	at org.jbake.app.ContentStore.<init>(ContentStore.java:63)
    	at org.jbake.app.DBUtil.createDataStore(DBUtil.java:15)
    	at org.jbake.app.ContentStoreIntegrationTest.setUpClass(ContentStoreIntegrationTest.java:14)
```

**Comment by OndraZizka** [comment]
PR #528
