### ISSUE TITLE
Use as library: Can't load "default.properties"

### ISSUE THREAD

**Issue by lefou** [jbake-org/jbake#596]
When using JBake as library in an isolated classloader, an exception is thrown, indicating that the "default.propeties" files can't be loaded. Althoght a file "default.properties" is located inside the `jbake-core.jar" as expected.

The setup is as follows:
* The JBake dist ZIP 2.6.4 is extracted into a `jbake-dist` dir
* An  `java.net.URLClassLoader`is created with all JAR from `jbake-dist/lib/` dir, but no parent classloader
* The `org.jbake.launcher.Main` class is loaded and the `main` method invoked
* The following exception is thrown:

```
Caused by: org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source default.properties
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
        at org.apache.commons.configuration.AbstractFileConfiguration.<init>(AbstractFileConfiguration.java:158)
        at org.apache.commons.configuration.PropertiesConfiguration.<init>(PropertiesConfiguration.java:252)
        at org.jbake.app.configuration.ConfigUtil.load(ConfigUtil.java:47)
        at org.jbake.app.configuration.ConfigUtil.loadConfig(ConfigUtil.java:58)
        at org.jbake.app.configuration.JBakeConfigurationFactory.createDefaultJbakeConfiguration(JBakeConfigurationFactory.java:29)
        at org.jbake.launcher.Main.run(Main.java:78)
```

## Details

A sketch of the code (Sala):
```scala
val cl = new URLClassLoader(classpath, null)
val mainClass = cl.loadClass("org.jbake.launcher.Main")
val mainMethod = mainClass.getMethod("main", Seq(classOf[Array[String]]): _*)
mainMethod.invoke(null, args)
```

The JARs in the classloader:
```
Creating Classloader with classpath: [Vector(/tmp/jbake-2.6.4-bin/lib/args4j-2.33.jar,
 /tmp/jbake-2.6.4-bin/lib/asciidoctorj-1.5.8.1.jar,
 /tmp/jbake-2.6.4-bin/lib/asciidoctorj-diagram-1.5.11.jar,
 /tmp/jbake-2.6.4-bin/lib/asm-5.0.3.jar,
 /tmp/jbake-2.6.4-bin/lib/asm-analysis-5.0.3.jar,
 /tmp/jbake-2.6.4-bin/lib/asm-tree-5.0.3.jar,
 /tmp/jbake-2.6.4-bin/lib/asm-util-5.0.3.jar,
 /tmp/jbake-2.6.4-bin/lib/attoparser-2.0.5.RELEASE.jar,
 /tmp/jbake-2.6.4-bin/lib/autolink-0.6.0.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-collections-3.2.2.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-configuration-1.10.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-io-2.6.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-jexl-2.1.1.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-lang-2.6.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-lang3-3.8.1.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-logging-1.2.jar,
 /tmp/jbake-2.6.4-bin/lib/commons-vfs2-2.2.jar,
 /tmp/jbake-2.6.4-bin/lib/concurrentlinkedhashmap-lru-1.4.2.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-abbreviation-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-anchorlink-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-aside-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-autolink-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-definition-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-emoji-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-escaped-character-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-footnotes-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-gfm-strikethrough-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-gfm-tasklist-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-ins-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-jekyll-front-matter-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-superscript-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-tables-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-toc-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-typographic-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-wikilink-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-ext-yaml-front-matter-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-formatter-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-jira-converter-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-profile-pegdown-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/flexmark-util-0.40.8.jar,
 /tmp/jbake-2.6.4-bin/lib/freemarker-2.3.28.jar,
 /tmp/jbake-2.6.4-bin/lib/groovy-2.5.5.jar,
 /tmp/jbake-2.6.4-bin/lib/groovy-dateutil-2.5.5.jar,
 /tmp/jbake-2.6.4-bin/lib/groovy-templates-2.5.5.jar,
 /tmp/jbake-2.6.4-bin/lib/groovy-xml-2.5.5.jar,
 /tmp/jbake-2.6.4-bin/lib/jade4j-1.2.7.jar,
 /tmp/jbake-2.6.4-bin/lib/javassist-3.20.0-GA.jar,
 /tmp/jbake-2.6.4-bin/lib/javax.servlet-api-3.1.0.jar,
 /tmp/jbake-2.6.4-bin/lib/jbake-core-2.6.4.jar,
 /tmp/jbake-2.6.4-bin/lib/jbake-dist-2.6.4.jar,
 /tmp/jbake-2.6.4-bin/lib/jcommander-1.35.jar,
 /tmp/jbake-2.6.4-bin/lib/jetty-http-9.2.26.v20180806.jar,
 /tmp/jbake-2.6.4-bin/lib/jetty-io-9.2.26.v20180806.jar,
 /tmp/jbake-2.6.4-bin/lib/jetty-server-9.2.26.v20180806.jar,
 /tmp/jbake-2.6.4-bin/lib/jetty-util-9.2.26.v20180806.jar,
 /tmp/jbake-2.6.4-bin/lib/jna-4.5.0.jar,
 /tmp/jbake-2.6.4-bin/lib/jna-platform-4.5.0.jar,
 /tmp/jbake-2.6.4-bin/lib/jruby-complete-9.1.17.0.jar,
 /tmp/jbake-2.6.4-bin/lib/json-simple-1.1.1.jar,
 /tmp/jbake-2.6.4-bin/lib/jsoup-1.11.3.jar,
 /tmp/jbake-2.6.4-bin/lib/jul-to-slf4j-1.7.25.jar,
 /tmp/jbake-2.6.4-bin/lib/logback-classic-1.2.3.jar,
 /tmp/jbake-2.6.4-bin/lib/logback-core-1.2.3.jar,
 /tmp/jbake-2.6.4-bin/lib/logging, /tmp/jbake-2.6.4-bin/lib/ognl-3.1.12.jar,
 /tmp/jbake-2.6.4-bin/lib/orientdb-core-2.2.37.jar,
 /tmp/jbake-2.6.4-bin/lib/parboiled-core-1.1.7.jar,
 /tmp/jbake-2.6.4-bin/lib/parboiled-java-1.1.7.jar,
 /tmp/jbake-2.6.4-bin/lib/pegdown-1.6.0.jar,
 /tmp/jbake-2.6.4-bin/lib/slf4j-api-1.7.25.jar,
 /tmp/jbake-2.6.4-bin/lib/snappy-java-1.1.0.1.jar,
 /tmp/jbake-2.6.4-bin/lib/thymeleaf-3.0.11.RELEASE.jar,
 /tmp/jbake-2.6.4-bin/lib/unbescape-1.1.6.RELEASE.jar)]
```

The JVM:
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (IcedTea 3.10.0) (Gentoo icedtea-3.10.0)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by ancho** [comment]
Can you try to enable the debug logging for `org.apache.commons.configuration`? This should give more hints what's actualy going on.

**Comment by ancho** [comment]
I will try to reproduce the behaviour in the next days. Don't know if I find time today.

**Comment by ancho** [comment]
Ok. In order to enable logback over the commons logging stuff one have to add jcl-over-slf4j.jar to the classpath it seems....which is currently not the case....

**Comment by lefou** [comment]
Here is the trace level debug output:

```
13:32:53.708 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to jbake.properties
13:32:53.710 DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:32:53.714 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /home/lefou/work/lepetitfou/blog/lefou.github.io/src, name is jbake.properties
13:32:53.714 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file jbake.properties at /home/lefou/work/lepetitfou/blog/lefou.github.io/src: no protocol: /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:32:53.714 DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /home/lefou/work/lepetitfou/blog/lefou.github.io/src/jbake.properties
13:32:53.725 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to default.properties
13:32:53.725 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is default.properties
13:32:53.725 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file default.properties at null: no protocol: default.properties
```

And as a reference, the output, when run as a successful standalone Java process:
```13:34:26.448 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to jbake.properties
13:34:26.450 DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:34:26.453 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /home/lefou/work/lepetitfou/blog/lefou.github.io/src, name is jbake.properties
13:34:26.454 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file jbake.properties at /home/lefou/work/lepetitfou/blog/lefou.github.io/src: no protocol: /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:34:26.454 DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /home/lefou/work/lepetitfou/blog/lefou.github.io/src/jbake.properties
13:34:26.466 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to default.properties
13:34:26.467 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is default.properties
13:34:26.467 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file default.properties at null: no protocol: default.properties
13:34:26.467 DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the context classpath (default.properties)
13:34:26.467 DEBUG o.a.c.c.PropertiesConfiguration - Base path set to jar:file:/home/lefou/work/lepetitfou/blog/lefou.github.io/out/site/jbakeDistributionDir/dest/unpacked/jbake-2.6.4-bin/lib/jbake-core-2.6.4.jar!/default.properties
```

**Comment by lefou** [comment]
Looks like the thread context class loaded is used but unset.

**Comment by lefou** [comment]
After setting the TCCL, it almost works. It now shows another exception, which could be related to the fact, that I had to surround the main method invocation with a Java SecurityManager to avoid the `System.exit` killing my tool process. Though, it should allow everthing except system exit.

Here's the new output:
```
13:44:56.267 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to jbake.properties
13:44:56.269 DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:44:56.273 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /home/lefou/work/lepetitfou/blog/lefou.github.io/src, name is jbake.properties
13:44:56.273 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file jbake.properties at /home/lefou/work/lepetitfou/blog/lefou.github.io/src: no protocol: /home/lefou/work/lepetitfou/blog/lefou.github.io/src
13:44:56.273 DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /home/lefou/work/lepetitfou/blog/lefou.github.io/src/jbake.properties
13:44:56.285 DEBUG o.a.c.c.PropertiesConfiguration - FileName set to default.properties
13:44:56.285 DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is default.properties
13:44:56.285 DEBUG o.a.c.c.DefaultFileSystem - Could not locate file default.properties at null: no protocol: default.properties
13:44:56.286 DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the context classpath (default.properties)
13:44:56.286 DEBUG o.a.c.c.PropertiesConfiguration - Base path set to jar:file:/home/lefou/work/lepetitfou/blog/lefou.github.io/out/site/jbakeDistributionDir/dest/unpacked/jbake-2.6.4-bin/lib/jbake-core-2.6.4.jar!/default.properties
JBake v2.6.4 (2019-01-21 21:03:37PM) [http://jbake.org]

13:44:57.110 INFO  org.jbake.app.Oven - Baking has started...
13:44:57.369 ERROR c.o.o.c.engine.memory.OEngineMemory - MBean for byte buffer pool cannot be registered
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
```

So, I have a workaround, but i think, the TCCL should be managed by JBake itself, as it is also (at least partly) designed to be used as a library.

**Comment by ancho** [comment]
All right. I think we just need to locate the default.properties file via the classloader and add that path directly to the `PropertiesConfiguration` class on instantiation.

**Comment by lefou** [comment]
Yep, that would be the best, because explicit, solution.
