### ISSUE TITLE
baking content files doesn't work with UTF-8 encoding and changed metadata

### ISSUE THREAD

**Issue by BogdanEM** [jbake-org/jbake#606]
I have a simple site with Freemarker templates and some simple HTML content files. 

When I bake the site, some content files are not written to the output directory. I played a bit with the content and the files and, from what I can figure out, it has something to do with encoding of the content files and the header metadata.

I can reproduce it on the `example_project_freemarker.zip` project like this:
- go to an empty folder
- run `jbake -i`
- go into the `content/about.html` file, change the file encoding to UTF-8 and the headers like this:
```
type=page
status=published
title=About
~~~~~~
```
- run `jbake -b`

The `about.html` will never be written in the output folder.

I'm using jbake v2.6.4, on Windows, with Java 1.8.

In the console I have some warnings:
```
19:08:38.875 WARN  org.jbake.template.TemplateEngines - unable to load engine
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.jbake.template.TemplateEngines.tryLoadEngine(TemplateEngines.java
:79)
        at org.jbake.template.TemplateEngines.registerEngine(TemplateEngines.jav
a:111)
        at org.jbake.template.TemplateEngines.loadEngines(TemplateEngines.java:1
02)
        at org.jbake.template.TemplateEngines.<init>(TemplateEngines.java:51)
        at org.jbake.template.DelegatingTemplateEngine.<init>(DelegatingTemplate
Engine.java:39)
        at org.jbake.app.Renderer.<init>(Renderer.java:82)
        at org.jbake.app.UtensilsFactory.createDefaultUtensils(UtensilsFactory.j
ava:26)
        at org.jbake.app.Oven.<init>(Oven.java:71)
        at org.jbake.launcher.Baker.bake(Baker.java:31)
        at org.jbake.launcher.Main.run(Main.java:97)
        at org.jbake.launcher.Main.run(Main.java:83)
        at org.jbake.launcher.Main.main(Main.java:56)
Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch

Exception Details:
  Location:
    org/codehaus/groovy/control/customizers/ASTTransformationCustomizer.<init>(L
java/lang/Class;)V @171: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 234d 05bd 006e 5903 2b53 5904 2c12
    0x0000010: c132 2bb9 0072 0200 5359 10ff 1202 b800
    0x0000020: 762a 5fab 0000 01af 0000 000a b951 be33
    0x0000030: 0000 0059 bd3c 11f8 0000 008e e4d2 7468
    0x0000040: 0000 00b7 f226 4f65 0000 00ca 1cb4 ddcd
    0x0000050: 0000 00df 224d 0e57 0000 00fe 4441 e4ca
    0x0000060: 0000 0127 4c34 1502 0000 0148 589a 5432
    0x0000070: 0000 0167 6648 e9fd 0000 0184 5f5a 5903
    0x0000080: 3212 7eb8 0051 c000 7e5f 5904 32b8 0042
    0x0000090: c000 445f 5905 32b8 0082 c000 785f 5906
    0x00000a0: 3212 84b8 0051 c000 845f 57b7 0087 a701
    0x00000b0: 2e5f 5a59 0332 b800 42c0 0044 5f59 0432
    0x00000c0: b800 82c0 0078 5f59 0532 1284 b800 51c0
    0x00000d0: 0084 5f57 b700 89a7 0105 5f5a 5903 32b8
    0x00000e0: 0042 c000 445f 57b7 008c a700 f25f 5a59
    0x00000f0: 0332 124b b800 51c0 004b 5f57 b700 8fa7
    0x0000100: 00dd 5f5a 5903 3212 7eb8 0051 c000 7e5f
    0x0000110: 5904 32b8 0042 c000 445f 57b7 0092 a700
    0x0000120: be5f 5a59 0332 127e b800 51c0 007e 5f59
    0x0000130: 0432 b800 42c0 0044 5f59 0532 b800 82c0
    0x0000140: 0078 5f57 b700 95a7 0095 5f5a 5903 3212
    0x0000150: 7eb8 0051 c000 7e5f 5904 3212 4bb8 0051
    0x0000160: c000 4b5f 57b7 0098 a700 745f 5a59 0332
    0x0000170: b800 42c0 0044 5f59 0432 1284 b800 51c0
    0x0000180: 0084 5f57 b700 9ba7 0055 5f5a 5903 32b8
    0x0000190: 0042 c000 445f 5904 32b8 0082 c000 785f
    0x00001a0: 57b7 009d a700 385f 5a59 0332 127e b800
    0x00001b0: 51c0 007e 5f59 0432 b800 42c0 0044 5f59
    0x00001c0: 0532 1284 b800 51c0 0084 5f57 b700 a0a7
    0x00001d0: 000d bb00 a259 12a4 b700 a7bf 57b1
  Stackmap Table:
    full_frame(@124,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@177,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@218,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@237,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@258,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@289,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@330,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@363,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@394,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@423,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@466,{UninitializedThis,Object[#68],Object[#122]},{Object[#124],U
ninitializedThis})
    full_frame(@476,{Object[#2],Object[#68],Object[#122]},{Object[#124]})

        at groovy.text.markup.MarkupTemplateEngine.<init>(MarkupTemplateEngine.j
ava:94)
        at groovy.text.markup.MarkupTemplateEngine.<init>(MarkupTemplateEngine.j
ava:125)
        at org.jbake.template.GroovyMarkupTemplateEngine.initializeTemplateEngin
e(GroovyMarkupTemplateEngine.java:53)
        at org.jbake.template.GroovyMarkupTemplateEngine.<init>(GroovyMarkupTemp
lateEngine.java:41)
        ... 16 common frames omitted
19:08:39.140 INFO  org.jbake.app.Oven - Baking has started...
```
and then this:

```
19:08:42.541 WARN  org.jbake.parser.MarkupEngine - Parsing skipped (missing type
 or status value in header meta data) for file D:\test\content\about.html!
19:08:42.541 WARN  org.jbake.app.Crawler - D:\test\content\about.html has an
 invalid header, it has been ignored!
```
**This last warning is false since the file has those header metadata. But maybe because `type` is first and UTF-8 has BOM characters somehow it doesn't register properly ?!?!?**

**Comment by BogdanEM** [comment]
The problem is indeed the BOM and the fact that `type` is the first header value. The key is not properly sanitized. See this code and the debug expressions:

![Clipboard02](https://user-images.githubusercontent.com/10814337/59688421-5b31b280-91e6-11e9-9dbb-4f2d9d671ac2.png)

In the image, the line is `type=page` but the test fails. The test with the sanitized line works.

**A workaround would be not to have `type` or `status` as the first line in the header,** and you can have both the template and the content pages as UTF-8 encoded.

**Comment by ancho** [comment]
Thank you. I'm not using windows that often. Can you post the full output of `java -version`.
If I spin up a VM I want to be sure I'm able to reproduce your observation as close as possible.
Are there any special locale settings I should be aware of?

**Comment by ancho** [comment]
Of course, Pull-Request are always welcome ;)

**Comment by BogdanEM** [comment]
My Java version is this:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

No special locale settings. English (United States)

This is a problem with Java, not jBake (ex: https://stackoverflow.com/questions/9876111/java-utf-8-and-bom), bu the jBake code could be changed to workaround the issue.

**Comment by ancho** [comment]
Yes. Thank you. We had a similar problem #257 which was fixed a while ago.
